version: 2
updates:
- package-ecosystem: gomod
  directory: "/src"
  schedule:
    interval: daily
    time: "23:30"
    timezone: America/New_York
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
    timezone: America/New_York
  open-pull-requests-limit: 10
